
spring:
  datasource:
    name: test
    jdbcUrl: jdbc:mysql://111.230.95.22:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: Shen123...
    driver-class-name: com.mysql.jdbc.Driver
    maxConnectionsPerPartition: 15
    minConnectionsPerPartition : 5
    partitionCount : 3
    acquireIncrement : 5
    statementsCacheSize : 100
server:
  port: 4001

  #upload file
constants:
    imageServerPath: http://webdev05.sstparts.com/
    uploadItemForumImagePath: /media/userfiles/po/itemforums/
    showItemForumImagePath: /po/itemforums/
    #itemForumImagePath: D://media/userfiles/po/itemforums/
    #redis集群
redis:
    host: 127.0.0.1
#    host: 192.168.1.111
    port: 6379
    timeout: 20000
#    集群环境打开下面注释，单机不需要打开
#    cluster:
#      集群信息
#      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
#      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
#      maxRedirects: 3
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
    password: shen
